from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MCP_SERVER_DIR = ROOT / "tools" / "mcp_server"
sys.path.insert(0, str(MCP_SERVER_DIR))

from schemas import TOOL_DEFINITIONS  # noqa: E402
from tool_visibility import disabled_definitions, visible_definitions  # noqa: E402
from version import __version__  # noqa: E402


START_MARKER = "<!-- BEGIN GENERATED MCP TOOL CATALOG -->"
END_MARKER = "<!-- END GENERATED MCP TOOL CATALOG -->"
RISK_LABELS = {
    "readonly": "readonly",
    "local_write": "local_write",
    "project_write": "project_write",
    "target_change": "target_change",
}


@dataclass(frozen=True)
class EmbeddedTarget:
    path: Path
    catalog_link: str
    intro: str


EMBEDDED_TARGETS = (
    EmbeddedTarget(
        ROOT / "README.md",
        "skills/br-plc-toolchain/references/mcp-tools.md",
        "当前 MCP 工具清单：",
    ),
    EmbeddedTarget(
        ROOT / "tools" / "mcp_server" / "README_FOR_LOCAL.md",
        "../../skills/br-plc-toolchain/references/mcp-tools.md",
        "当前 stdio MCP 暴露以下工具：",
    ),
    EmbeddedTarget(
        ROOT / "docs" / "PLC_MCP_SKILL_PROMPT_ROADMAP.md",
        "../skills/br-plc-toolchain/references/mcp-tools.md",
        "当前已实现工具：",
    ),
)
CATALOG_PATH = ROOT / "skills" / "br-plc-toolchain" / "references" / "mcp-tools.md"


def markdown_escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\r", " ").replace("\n", " ").strip()


def tool_rows() -> list[str]:
    rows = []
    for definition in visible_definitions():
        name = definition["name"]
        schema = definition["inputSchema"]
        meta = definition.get("_meta") or {}
        risk = str(meta.get("br-automation/riskLevel") or "unknown")
        backend = str(meta.get("br-automation/backend") or "unknown")
        required = set(schema.get("required") or [])
        confirmation = "`execute=true`" if "execute" in required else "-"
        rows.append(
            "| `{}` | `{}` | `{}` | {} | {} |".format(
                markdown_escape(name),
                markdown_escape(RISK_LABELS.get(risk, risk)),
                markdown_escape(backend),
                confirmation,
                markdown_escape(definition.get("description") or ""),
            )
        )
    return rows


def hidden_note() -> str:
    hidden = [definition["name"] for definition in disabled_definitions()]
    if not hidden:
        return ""
    names = ", ".join(f"`{markdown_escape(name)}`" for name in hidden)
    return "\n".join(
        [
            "",
            "## Hidden Tools",
            "",
            f"以下 {len(hidden)} 个工具被 `config/mcp/tool_filter.json` 隐藏（实现仍注册，仅供内部编排调用，MCP 列表与直接调用不可用）：",
            "",
            names,
            "",
        ]
    )


def render_table() -> str:
    return "\n".join(
        [
            "| MCP Tool | Risk | Backend | Confirmation | Description |",
            "| --- | --- | --- | --- | --- |",
            *tool_rows(),
        ]
    )


def render_catalog() -> str:
    return "\n".join(
        [
            "# MCP Tool Catalog",
            "",
            "<!-- Generated by scripts/maintenance/generate_mcp_docs.py. Do not edit manually. -->",
            "",
            f"MCP server version: `{__version__}`",
            "",
            render_table(),
            "",
            hidden_note(),
            "## Risk Levels",
            "",
            "- `readonly`: reads configuration or artifacts without writing local state.",
            "- `local_write`: writes local build output, catalogs, logs, or reports.",
            "- `project_write`: changes Automation Studio project structure or configuration.",
            "- `target_change`: changes ARsim/PLC process state or PLC variables.",
            "",
            "`project_write` and `target_change` tools require `execute=true`.",
            "",
        ]
    )


def render_embedded(target: EmbeddedTarget) -> str:
    return "\n".join(
        [
            target.intro,
            "",
            f"MCP server version: `{__version__}`. Full catalog: [{target.catalog_link}]({target.catalog_link})",
            "",
            render_table(),
            "",
            hidden_note(),
        ]
    )


def replace_generated_region(text: str, generated: str, path: Path) -> str:
    if text.count(START_MARKER) != 1 or text.count(END_MARKER) != 1:
        raise ValueError(f"expected exactly one generated MCP catalog region in {path}")
    before, remainder = text.split(START_MARKER, 1)
    _, after = remainder.split(END_MARKER, 1)
    return f"{before}{START_MARKER}\n{generated.rstrip()}\n{END_MARKER}{after}"


def expected_outputs() -> dict[Path, str]:
    outputs = {CATALOG_PATH: render_catalog()}
    for target in EMBEDDED_TARGETS:
        current = target.path.read_text(encoding="utf-8-sig")
        outputs[target.path] = replace_generated_region(current, render_embedded(target), target.path)
    return outputs


def generate(*, check: bool) -> int:
    drifted: list[Path] = []
    for path, expected in expected_outputs().items():
        current = path.read_text(encoding="utf-8-sig") if path.exists() else ""
        if current == expected:
            continue
        drifted.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("w", encoding="utf-8", newline="\n") as stream:
                stream.write(expected)

    if drifted:
        action = "out of date" if check else "updated"
        for path in drifted:
            print(f"{action}: {path.relative_to(ROOT)}")
    return 1 if check and drifted else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate MCP tool catalog documentation from schemas.py.")
    parser.add_argument("--check", action="store_true", help="Fail when generated documentation is out of date.")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
