{
  "strHex00": "<%ReadPLC("gstAspInface.stToAsp.strDataST1[0]");%>",
  "strHex01": "<%ReadPLC("gstAspInface.stToAsp.strDataST1[1]");%>",
  "strHex02": "<%ReadPLC("gstAspInface.stToAsp.strDataST1[2]");%>",
  "strHex03": "<%ReadPLC("gstAspInface.stToAsp.strDataST1[3]");%>",
  "strHex04": "<%ReadPLC("gstAspInface.stToAsp.strDataST1[4]");%>",
  "strHex05": "<%ReadPLC("gstAspInface.stToAsp.strDataST1[5]");%>",

  "strHex10": "<%ReadPLC("gstAspInface.stToAsp.strDataST2[0]");%>",
  "strHex11": "<%ReadPLC("gstAspInface.stToAsp.strDataST2[1]");%>",
  "strHex12": "<%ReadPLC("gstAspInface.stToAsp.strDataST2[2]");%>",
  "strHex13": "<%ReadPLC("gstAspInface.stToAsp.strDataST2[3]");%>",
  "strHex14": "<%ReadPLC("gstAspInface.stToAsp.strDataST2[4]");%>",
  "strHex15": "<%ReadPLC("gstAspInface.stToAsp.strDataST2[5]");%>",

  "strHex20": "<%ReadPLC("gstAspInface.stToAsp.strDataST3[0]");%>",
  "strHex21": "<%ReadPLC("gstAspInface.stToAsp.strDataST3[1]");%>",
  "strHex22": "<%ReadPLC("gstAspInface.stToAsp.strDataST3[2]");%>",
  "strHex23": "<%ReadPLC("gstAspInface.stToAsp.strDataST3[3]");%>",
  "strHex24": "<%ReadPLC("gstAspInface.stToAsp.strDataST3[4]");%>",
  "strHex25": "<%ReadPLC("gstAspInface.stToAsp.strDataST3[5]");%>",

  "strHex30": "<%ReadPLC("gstAspInface.stToAsp.strDataST4[0]");%>",
  "strHex31": "<%ReadPLC("gstAspInface.stToAsp.strDataST4[1]");%>",
  "strHex32": "<%ReadPLC("gstAspInface.stToAsp.strDataST4[2]");%>",
  "strHex33": "<%ReadPLC("gstAspInface.stToAsp.strDataST4[3]");%>",
  "strHex34": "<%ReadPLC("gstAspInface.stToAsp.strDataST4[4]");%>",
  "strHex35": "<%ReadPLC("gstAspInface.stToAsp.strDataST4[5]");%>",

  "strHex40": "<%ReadPLC("gstAspInface.stToAsp.strDataST5[0]");%>",
  "strHex41": "<%ReadPLC("gstAspInface.stToAsp.strDataST5[1]");%>",
  "strHex42": "<%ReadPLC("gstAspInface.stToAsp.strDataST5[2]");%>",
  "strHex43": "<%ReadPLC("gstAspInface.stToAsp.strDataST5[3]");%>",
  "strHex44": "<%ReadPLC("gstAspInface.stToAsp.strDataST5[4]");%>",
  "strHex45": "<%ReadPLC("gstAspInface.stToAsp.strDataST5[5]");%>",

  "strHex50": "<%ReadPLC("gstAspInface.stToAsp.strDataST6[0]");%>",
  "strHex51": "<%ReadPLC("gstAspInface.stToAsp.strDataST6[1]");%>",
  "strHex52": "<%ReadPLC("gstAspInface.stToAsp.strDataST6[2]");%>",
  "strHex53": "<%ReadPLC("gstAspInface.stToAsp.strDataST6[3]");%>",
  "strHex54": "<%ReadPLC("gstAspInface.stToAsp.strDataST6[4]");%>",
  "strHex55": "<%ReadPLC("gstAspInface.stToAsp.strDataST6[5]");%>",

  "diWindowWidth":         "<%ReadPLC("gstAspInface.stToAsp.diWindowWidth");%>",
  "usiCmdLatchPos":        "<%ReadPLC("gstAspInface.stToAsp.usiCmdLatchPos");%>",
  "udiCurLatchPosition":   "<%ReadPLC("gstAspInface.stToAsp.udiCurLatchPosition");%>",
  "diPuWindowIntervalmm":  "<%ReadPLC("gstAspInface.stToAsp.diPuWindowIntervalmm");%>",
  "usiActiveDrawMode":     "<%ReadPLC("gstAspInface.stToAsp.usiActiveDrawMode");%>",
  "diSImage":              "<%ReadPLC("gstAspInface.stToAsp.diSImage");%>",
  "udiMarkSelfPosition":   "<%ReadPLC("gstAspInface.stToAsp.udiMarkSelfPosition");%>",
  "udiMarkFirstPosition":   "<%ReadPLC("gstAspInface.stToAsp.udiMarkFirstPosition");%>",
  "udiMarkFrontPosition":   "<%ReadPLC("gstAspInface.stToAsp.udiMarkFrontPosition");%>",
  "usiMarkEnableBST":       "<%ReadPLC("gstAspInface.stToAsp.usiMarkEnableBST");%>"
}